#!/bin/bash

export YELL_COLOR='\E[33m'        # Red BG
export FINE_COLOR='\E[32m'        # Green BG
export NORM_COLOR='\E[0m'         # Normalize BG


echo -e "\n\n$YELL_COLOR Download repo file ... $NORM_COLOR"
udo curl http://commondatastorage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
sudo chmod 755 /usr/local/bin/repo
sudo apt-get update
sudo apt-get upgrade -y

echo -e "\n\n$YELL_COLOR Installing Editors and plugins... $NORM_COLOR"
sudo apt-get install vim -y

echo -e "\n\n$YELL_COLOR Installing internet based tools... $NORM_COLOR"
sudo apt-get install curl axel html2text vnstat scrot bc -y

echo -e "\n\n$YELL_COLOR Installing system based tools... $NORM_COLOR"
sudo apt-get install dpkg-dev cifs-utils openssh-server openssh-client gdisk \
        git synaptic p7zip-rar unetbootin nfs-common nfs-kernel-server -y

echo -e "\n\n$YELL_COLOR Installing dev tools... $NORM_COLOR"
sudo apt-get install libftdi-dev minicom build-essential \
        python-software-properties android-tools-adb android-tools-fastboot \
        libncurses5-dev lib32ncurses5 lib32z1 lib32stdc++6 ant bc bison \
        build-essential curl flex g++-multilib gcc-multilib git-core gnupg gperf lbzip2 \
        lib32ncurses5-dev libc6-dev libgl1-mesa-dev:i386 libncurses5-dev libreadline5:i386 \
        libreadline6-dev:i386 libx11-dev:i386 libxml2-utils pigz python-markdown python-matplotlib \
        python-numpy python-scipy tofrodos x11proto-core-dev xsltproc zip zlib1g-dev:i386 -y

#echo -e "\n\n$YELL_COLOR Installing ARM compile support... $NORM_COLOR"
#sudo apt-get install gcc-arm-linux-gnueabi binutils-arm-linux-gnueabi gcc-arm-linux-gnueabihf -y

echo -e "\n\n$YELL_COLOR Installing multimedia tools... $NORM_COLOR"
sudo apt-get install libav-tools ubuntu-restricted-extras -y

echo -e "\n\n$FINE_COLOR Installation completed successfully... $NORM_COLOR"
echo "export PS1='\u@\W$ '" >> /root/.bashrc
echo "export PS1='\u@\W$ '" >> $HOME/.bashrc
